### ISSUE TITLE
Support GIT_OBJECT_DIRECTORY environment variable

### ISSUE THREAD

**Issue by acbits** [gitpython-developers/GitPython#1000]
When using GIT_OBJECT_DIRECTORY to store git objects, a statement like
git.Repo('someproject') fails. This is due to is_git_dir() in git/repo/fun.py making an assumption that there will be a objects directory under .git which isn't the case when GIT_OBJECT_DIRECTORY is defined and being used.

A fix like the attached patch should solve the problem, though there might be more fixes needed in other places. This fix alone solves my particular workflow for now.

```
diff --git a/git/repo/fun.py b/git/repo/fun.py
index 784a70bf3..e3a7bc57a 100644
--- a/git/repo/fun.py
+++ b/git/repo/fun.py
@@ -35,7 +35,8 @@ def is_git_dir(d):
             There is the unlikely danger to throw if we see directories which just look like a worktree dir,
             but are none."""
     if osp.isdir(d):
-        if osp.isdir(osp.join(d, 'objects')) and osp.isdir(osp.join(d, 'refs')):
+        if (osp.isdir(osp.join(d, 'objects')) or os.environ.has_key('GIT_OBJECT_DIRECTORY')) \
+           and osp.isdir(osp.join(d, 'refs')):
             headref = osp.join(d, 'HEAD')
             return osp.isfile(headref) or \
                 (osp.islink(headref) and

```

**Comment by Byron** [comment]
Thanks a lot! You are probably right - the fix won't work in all cases, especially since GitPython has an optional pure-python object database implementation which certainly doesn't pick that up.

However, I believe it's worth having this fix to improve the situation in the most common case.

It looks like the patch fails on CI, but due to travis not being accessible from my current location, I don't really see what it is. Will keep you posted.

**Comment by Byron** [comment]
Great, I moved the project to github actions, and now the patch is included.
Today or tomorrow I will create a  new release as well.
