### ISSUE TITLE
'--relative' option doesn't work with GitCMD  repo.git.format_patch("--relative", "--output-directory", outdir, commit, "-1")

### ISSUE THREAD

**Issue by sophy228** [gitpython-developers/GitPython#1001]
```python
#filepath = self.repo.git.format_patch("--relative", "--output-directory", outdir, commit, "-1")
pip = os.popen("git format-patch  --relative -o {} {} -1".format(outdir, commit))
filepath = pip.readline().strip()
pip.close()
```

The "--relative" doesn't make any effect in first line, so I have to use the following lines instead, and they can work...

No idea what is difference

**Comment by Byron** [comment]
Thanks for letting us know.
It can be that the GitPython git command wrapper reorders some arguments, which sometimes yields unexpected results due to to `git` not always parsing its arguments the way one would expect.

If desired, you could debug this and see what GitPython actually invokes using [the tips provided in the documentation](https://gitpython.readthedocs.io/en/stable/tutorial.html#git-command-debugging-and-customization).

For now I am closing the issue, as there is probably nothing GitPython can do to improve the situation, at least not without risking breaking other git invocations in the process, and since there is a working workaround.

Thanks for your understanding.
