### ISSUE TITLE
Submodule .repo points to parent repo instead of configured submodule repository

### ISSUE THREAD

**Issue by jmartens** [gitpython-developers/GitPython#1003]
When iterating over the submodules of a repository and accessing it's repo property it turns out the object returned is the parent repository instead of the configured repository for this submodule, making this simple test case fail:

```
for sumbodule in repo.submodules:
    assert not submodule.repo == repo
```

The abspath seems to point to the location of the submodule so in order to assess the state of the submodule repository status I have to do:

```
for submodule in repo.submodules:
    submodule_repo = Repo(submodule.abspath)
    assert not submodule_repo == repo
```

I would have expected that the `.repo` property of the submodule would reference the repository details of the submodule, not the parent repository it is configured in.

**Comment by Byron** [comment]
Thanks for taking the time describe the issue and make it easy to understand.

I can only agree, and by looking at the code, I would also expect `repo` to point to the submodule repository.

It's great to see the workaround here as well.
After glancing [at the documentation](https://gitpython.readthedocs.io/en/stable/tutorial.html#submodule-handling) it appears that `submodule.module()` might be the way to obtain the repository. Maybe that's worth at try. [Here is additional examples](https://gitpython.readthedocs.io/en/stable/tutorial.html#advanced-repo-usage) on how to interact with this API.

As this API cannot be fixed without breakage, and since there are alternatives to using `submodule.repo`, I believe it's fair to close this issue.

If you feel differently or would like to make suggestions on how to fix this without breakage, please let us know in the comments.

**Comment by jmartens** [comment]
Thanks for pointing me in the `submodule.module()` direction, that seems to represent a `Repo` object on which I can run my checks, without casting a new `Repo` object from the absolute path of the submodule.

> I can only agree, and by looking at the code, I would also expect `repo` to point to the submodule repository.

I was and am puzzeled by this as well ...

> As this API cannot be fixed without breakage

... and wonder what would break, despite I did not investigate and have no need to now) in the API if this would be changed.

**Comment by Byron** [comment]
<img width="385" alt="Screenshot 2020-04-23 at 08 45 13" src="https://user-images.githubusercontent.com/63622/80046975-c488fd00-853e-11ea-811d-85d0427afe6f.png">

As GitPython is used by a tremendous amount of packages, at least so it seems, it's safe to assume somewhere submodule.repo is used and the code expects it to be what it is right now.

Changing semantics thus would be a breaking change, which would require a major version bump to deploy safely.

Currently there is no process for scheduling these changes into one, big release, and I would try to avoid major version bumps for small, non-critical changes.

However, I am sure there would be a way to add a new member, or to make `module()` more discoverable.
