### ISSUE TITLE
3.1.7: No tests in sdist

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/GitPython#1037]
Hi! When trying to package 3.1.7 for Arch Linux I found the sdist to not have any tests anymore.
What is the rationale behind the removal in https://github.com/gitpython-developers/GitPython/commit/7e7045c4a2b2438adecd2ba59615fbb61d014512?
How can I test this package against the distribution's packages and Python version now?

I can't use the tarballs on github as source tarballs as they are missing a PGP signature. The tags themselves are signed using an unknown PGP key (`EE029D1E5EB40300`): https://github.com/gitpython-developers/GitPython/tags

**Comment by Byron** [comment]
Thanks for the headsup, and my apologies for the hassle.
The idea behind the mentioned commit is to reduce the package size so that distribution and delivery speed is improved, saving internet resources. Repackaging and running tests is a special case that probably is better suited with cloning the repository or using the tarball.

The latter should work very similarly to what worked before when using the package from pypi, and I am sure there are already mechanisms in place to allow the tests to run without a prior clone. If there are new problems related to this, please let me know nonetheless, but the general idea is to run `./init-tests-after-clone.sh` to put the repository in a state that satisfies the preconditions of the GitPython tests.

Lastly, I have updated the tag 3.1.7 and signed it with 2CF6E0B51AAF73F09B1C21174D1DA68C88710E60. Furthermore, I changed my repository configuration to force me signing everything with said key as well to prevent this from happening in the future.

If there is anything else, I am happy to help.

**Comment by dvzrv** [comment]
> or using the tarball.

The pypi sdist *is* a source tarball.
The sources should always be made available for being able to test them against the environment at hand.

A wheel package on the other hand often bundles things and does not need to take care of the environment at hand (apart from the interpreter version maybe).

So having tests in a source tarball is a very valid use-case (not only for distributions).

Lastly I would like to add, that I'm currently using a git clone of this repository, as it can be validated more easily.

**Comment by Byron** [comment]
Thanks for the explanation. So ideally, there would be a source tarball on pypi that contains the tests, but since the tests won't run anyway without their parent git repository, it's probably not very useful to have. Thus it appears to be the correct decision to drop tests everywhere and rely on the git repository to be available.

In order to assure the sources in the tarball or wheel package indeed correlate to the tested tag in the repository, [this script (or similar)](https://github.com/gitpython-developers/GitPython/issues/765#issuecomment-396072153) could be used to match the source with the git tree.

If this helps or gets voided due to Arch support being dropped as per #1055, please feel free to close the issue.

**Comment by Byron** [comment]
As part of spring cleaning, I am closing this issue as it was opened more than four months ago while still asking for feedback.

If this is a mistake or any other action should rather be taken, please let me know in the comments or create a new issue as digest of this one.
Thanks for your understanding and the work that undoubtedly went into this.
