### ISSUE TITLE
Documentation needs update: "How to setup a new remote"

### ISSUE THREAD

**Issue by christoffertoft** [gitpython-developers/GitPython#1065]
Hi guys, and thanks for a cool project! I find that documentation is sorely lacking in some areas unfortunately. 

Under the "Remotes handling" chapter for example, we see this snippet:

```
empty_repo = git.Repo.init(os.path.join(rw_dir, 'empty'))
origin = empty_repo.create_remote('origin', repo.remotes.origin.url)
```
there's no indication on how to set up the remote, and judging from this code snippet it's already previously set up? The code doesnt work when I run it in a test script unfortunately.
Maybe creating some simple recipes in the documentation for oft-performed tasks would be an idea? 
Like "instantiate a new repo and set up remote". "integrate latest changes to local" "Push dirty state to remote"  - you get the idea

I think being super verbose in the documentation helps, both in limiting the number of issues the dev team has to answer and to increase adoption of the library, I think having to go directly to StackOverflow or similar to get answers about basic set up is a sign of lacking documentation:
https://stackoverflow.com/questions/28291909/gitpython-and-ssh-keys
https://stackoverflow.com/questions/41836988/git-push-via-gitpython

**Comment by Byron** [comment]
You have probably seen that this project is in maintenance mode, living of the work of maintainers and contributors alike.

Since this issue describes great places to get started with additional documentation beyond what's there, I invite everyone reading this in submitting PRs to add more documentation.

My personal take on this is that most people probably google what they need and will find stackoverflow in the process. Even if everything would be clearly described in GitPython's own documentation, it would probably have difficulty to compete with the page rank of stackoverflow and thus show up later, if at all.

As your particular problem seems to be resolved with the linked stackoverflow answers and knowing from experience that nobody will spend their free time to add documentation and resolve this issue, I am closing it.
