### ISSUE TITLE
Weird TemporaryDirectory created which never goes away

### ISSUE THREAD

**Issue by eosborne-vio** [gitpython-developers/GitPython#1115]
When I pull a repo, it creates an odd temporary file which never goes away.
This happens on Linux (Ubuntu 18.04, Python 3.6.9, gitPython 3.1.12 which is what I got from pip3).
It's very difficult to google this error because of the odd tempfile name.

Steps to reproduce:

```
from git import Repo
import tempfile
repo = Repo.clone_from('git@github.com:gitpython-developers/GitPython.git', tempfile.TemporaryDirectory())
```

This leaves me with a directory

```
eosborne@eosborne-salt-master:/tmp$ ls -ald *Temp*
drwxrwxr-x 3 eosborne eosborne 4096 Jan 27 12:42 '<TemporaryDirectory '\'''
```

```
eosborne@eosborne-salt-master:/tmp$ tree *Temp*
<TemporaryDirectory '
└── tmp
    └── tmpccab569v'>
        ├── AUTHORS
        ├── CHANGES
```

I think gitpython is calling `str(dirname)` and expecting just the directory name, but that's not what tempfile gives back:

```
In [12]: td = tempfile.TemporaryDirectory()

In [13]: td.name
Out[13]: '/var/folders/kd/bjhw84ss2x734frx98qh1mw40000gn/T/tmpgralfh9m'

In [14]: str(td)
Out[14]: "<TemporaryDirectory '/var/folders/kd/bjhw84ss2x734frx98qh1mw40000gn/T/tmpgralfh9m'>"
```

I believe this is an issue with the tempfile library but I could see fingers being pointed back and forth on this. I have opened a [python issue](https://bugs.python.org/issue43039) as well, so that both sides see the issue.

**Comment by Byron** [comment]
Indeed that would be an issue with `tempfile`, as it [seems to state](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) that the temporary directory is supposed to be removed automatically.

When it comes to GitPython, it does indeed expect [a string](https://github.com/gitpython-developers/GitPython/blob/master/git/repo/base.py#L948:L949) and converts it if needed.

To fix the issue with the incorrect path used, provide `td.name` to the GitPython instead of the `td` object itself.

Even though I close this issue, please feel free to keep posting follow up questions.

**Comment by eosborne-vio** [comment]
The Python core developers closed my issue and said that tempfile is working as designed.  That seems a little odd to me, but I'm not going to argue with them about the intent of their library.  I'm OK closing this and just letting it drop. It'd be cool if gitpython supported pass in a TemporaryDirectory() directly, but passing in .name is easy enough.

Thanks!
