### ISSUE TITLE
gitpython 3.1.20 not on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/GitPython#1345]
Currently [the last release on pypi.org is 3.1.18](https://pypi.org/project/GitPython/).

**Comment by Byron** [comment]
That's the latest working version, all others have been yanked due to various issues showing up due to typing or newly added timeouts.

<img width="830" alt="Screenshot 2021-09-18 at 09 24 07" src="https://user-images.githubusercontent.com/63622/133867557-e4c768aa-8c1d-4928-a8ae-20afa0f22700.png">

v3.1.24 should be releasable soon, it depends on #1340 .

**Comment by Byron** [comment]
https://pypi.org/project/GitPython/3.1.24/ was just released, let's hope this one can stay.
