### ISSUE TITLE
Push tags=True blocks on github

### ISSUE THREAD

**Issue by kylegibson** [gitpython-developers/GitPython#145]
As of last week, we could push tags using gitpython without any issue. Now it blocks forever. Neither git nor gitpython has been upgraded. This problem is occurring for multiple developers.

git versions: 1.8.5.2, 1.7.0.4

```
    remote.push(tags=True)
  File "/home/kyle/.python/local/lib/python2.7/site-packages/git/remote.py", line 627, in push
    return self._get_push_info(proc, progress or RemoteProgress())
  File "/home/kyle/.python/local/lib/python2.7/site-packages/git/remote.py", line 552, in _get_push_info
    digest_process_messages(proc.stderr, progress)
  File "/home/kyle/.python/local/lib/python2.7/site-packages/git/remote.py", line 48, in digest_process_messages
    char = fh.read(1)
  File "/home/kyle/.python/local/lib/python2.7/site-packages/async/__init__.py", line 21, in thread_interrupt_handler
    prev_handler(signum, frame)
KeyboardInterrupt
```

**Comment by Byron** [comment]
I will implement poll()-based parsing of stderr/stdout in case of fetch/pull/push now. The previous fixed was merged into a now obsolete branch, and would cost the real-time progress information that I was keen to have.

**Comment by Byron** [comment]
The chosen [implementation](https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L48) uses `poll()` if possible, but resorts to brute-force threads for 'pumping' lines otherwise. The only reason threads are less desirable is that they have more synchronisation overhead in general, and are note reused.
Using a threadpool could help alleviate this overhead.

Please also note that to my surprise, `poll()` is not available on py2 on OSX either, but is available on py3 on OSX.
On windows, there is no `poll()` either, and the existing `select()` call only works on sockets. Therefore using threads was the only viable alternate code-path that would work everywhere.
Also note that I managed to have the thread implementation occasionally fail on me, which could hint at some sync issue still present.

**Comment by msabramo** [comment]
Did you consider using kqueue on OS X?

Or stepping back, I wonder if you might use an existing event loop such as libev, libuv, etc.?

**Comment by Byron** [comment]
No, I didn't consider any of these, just because using Threads was 'good enough' as fallback.
If the named libraries wouldn't add another dependency, PR's would be very welcome.

**Comment by msabramo** [comment]
Yeah, I kind of figured that threads would be fairly easy and "good enough".

The other things would add dependencies and they're tricky ones as they're C extensions. You could use asyncio in Python 3.4 though that's a bit of work for a pretty small audience.

So probably what you have is good.

**Comment by Byron** [comment]
Let's hope so. After all, I still see these pseudo-random failures on py2, where lines on stderr get gobbled up as if characters are read out of order (which can't be for all I know) ... .
This kind of worries me, as it strongly points to my Thread implementation being somewhat incorrect. But I don't see the issue, maybe you can have a look ?
Interestingly, the issue seems to only show if I run `tox`.
