### ISSUE TITLE
Rename from/to is swapped (`a_path`/`b_path`) (how to diff worktree with index)

### ISSUE THREAD

**Issue by danthe3rd** [gitpython-developers/GitPython#1512]
# Repro
```
$ git init && echo "abc" > abc && git add abc && git commit -m "abc" && git mv abc def && python -c "import git; print(git.Repo('.').index.diff('HEAD')[0].b_path)"
Initialized empty Git repository in /Users/bugreport/.git/
[main (root-commit) e32bbcd] abc
 1 file changed, 1 insertion(+)
 create mode 100644 abc
abc
```

Expected output: "def" for `b_path`

Swapping the paths there [1] works, but I'm not sure why the tests [2] are passing in the CI. Might be due to git version?

**System info:**
```
$ git --version
git version 2.31.1
```

[1] https://github.com/gitpython-developers/GitPython/blob/main/git/diff.py#L615
[2] https://github.com/gitpython-developers/GitPython/blob/main/test/test_diff.py#L135

**Comment by Byron** [comment]
Thanks for posting the investigation - it's not the first time I hear about paths seemingly being swapped. Typically this is due to misaligned expectations. Here I'd think that the question of `index.diff('HEAD')` is actually: what are the changes needed to turn the index into `HEAD`, which is a reverse diff. 

What might shed some light on this is [the respective section of the docs](https://gitpython.readthedocs.io/en/stable/tutorial.html#obtaining-diff-information) even though I failed to see how one would diff the working tree against the index with that. Maybe this is the issue here, maybe it's not possible with the current API and one would have to logically reverse the diff by hand.

**Comment by danthe3rd** [comment]
Oh that's right! I just ran a few more tests, and an "add" change appears as a "delete" change, so it's indeed inverted

```
$ git init && touch README && git add README && git commit -m "readme" && echo "abc" > abc && git add abc && python -c "import git; diff=git.Repo('.').index.diff('HEAD')[0]; print('a', diff.a_path); print('b', diff.b_path); print('change_type', diff.change_type)"
Initialized empty Git repository in /Users/bugreport/.git/
[main (root-commit) 3666c8e] readme
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README
a abc
b abc
change_type D
```

Thanks a lot!
