### ISSUE TITLE
3.1.30 & 3.1.31: failing tests

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/GitPython#1557]
Hi! Since 3.1.30 there are  few failing tests:

```
FAILED ../../../../dev/git/ext/gitdb/gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_correctness
FAILED ../../../../dev/git/ext/gitdb/gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_loose_correctness
FAILED ../../../../dev/git/ext/gitdb/gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_pack_random_access
FAILED ../../../../dev/git/ext/gitdb/gitdb/test/performance/test_pack_streaming.py::TestPackStreamingPerformance::test_pack_writing
FAILED ../../../../dev/git/ext/gitdb/gitdb/test/performance/test_pack_streaming.py::TestPackStreamingPerformance::test_stream_reading
FAILED ../../../../dev/test/test_submodule.py::TestSubmodule::test_git_submodules_and_add_sm_with_new_commit
FAILED ../../../../dev/test/test_submodule.py::TestSubmodule::test_list_only_valid_submodules
==== 7 failed, 453 passed, 42 skipped, 20 deselected, 6 warnings in 47.15s =====
```
[python-gitpython-3.1.31-1-x86_64-build.log](https://github.com/gitpython-developers/GitPython/files/10876120/python-gitpython-3.1.31-1-x86_64-build.log)
[python-gitpython-3.1.31-1-x86_64-check.log](https://github.com/gitpython-developers/GitPython/files/10876121/python-gitpython-3.1.31-1-x86_64-check.log)

**Comment by Byron** [comment]
The first cause I found was `transport 'file' not allowed`. Unfortunately the test-suite isn't yet able to configure itself accordingly even though it would be possible by setting a few environment variables. Thus it's necessary to [set the configuration similar to how it's done on CI](https://github.com/gitpython-developers/GitPython/blob/f25333525425ee1497366fd300a60127aa652d79/.github/workflows/pythonpackage.yml#L56-L58).

The reason for this occurring now *should* be a more recent `git` executable, at least that's what seems to make most sense here.

For those seeing this, the issue could be fixed by setting the configuration variables linked above for the whole process before the test-suite launches by setting [these environment variables](https://git-scm.com/docs/git-config#Documentation/git-config.txt-GITCONFIGVALUEltngt).
