### ISSUE TITLE
Failing (or warning?) with Python 3.12 alpha 7

### ISSUE THREAD

**Issue by henryiii** [gitpython-developers/GitPython#1571]
I think things like this https://github.com/gitpython-developers/GitPython/blob/f25333525425ee1497366fd300a60127aa652d79/git/util.py#L180 is causing a problem, due to https://docs.python.org/3.12/whatsnew/3.12.html#shutil (see https://github.com/python/cpython/pull/102829 ). While I do have warnings as errors on in my test suite, this is not reporting a warning like `wheel` does, it's an error when calling `repo.index.commit("first commit")`:

```
/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages/git/refs/symbolic.py:172: in _get_ref_info_helper
    repodir = _git_dir(repo, ref_path)
        cls        = <class 'git.refs.head.Head'>
        ref_path   = 'refs/heads/main'
        repo       = <git.repo.base.Repo '/tmp/pytest-of-runner/pytest-0/test_plugin_metadata0/pkg/.git'>
        tokens     = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

repo = <git.repo.base.Repo '/tmp/pytest-of-runner/pytest-0/test_plugin_metadata0/pkg/.git'>
path = 'refs/heads/main'

    def _git_dir(repo: "Repo", path: Union[PathLike, None]) -> PathLike:
        """Find the git dir that's appropriate for the path"""
        name = f"{path}"
        if name in ["HEAD", "ORIG_HEAD", "FETCH_HEAD", "index", "logs"]:
            return repo.git_dir
>       return repo.common_dir
E       SystemError: <function Repo.common_dir at 0x7ffba93f3060> returned a result with an exception set

name       = 'refs/heads/main'
path       = 'refs/heads/main'
repo       = <git.repo.base.Repo '/tmp/pytest-of-runner/pytest-0/test_plugin_metadata0/pkg/.git'>

/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages/git/refs/symbolic.py:55: SystemError
```

GHA's `3.12-dev` just updated to alpha 7, which is why I am now seeing this error.

**Comment by Byron** [comment]
Thanks for reporting! Any help with this will be appreciated.

**Comment by EliahKagan** [comment]
Does this still happen with Python 3.12 RC2? Since #1654, Python 3.12 ([currently](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) at RC2) runs [on this project's CI](https://github.com/gitpython-developers/GitPython/blob/25597cbc05c7e478efc77bacd0f441962dbf87d5/.github/workflows/pythonpackage.yml#L18), and [all checks have been passing](https://github.com/gitpython-developers/GitPython/actions/workflows/pythonpackage.yml?query=branch%3Amain+event%3Apush). Based on https://github.com/python/cpython/issues/103632, https://github.com/python/cpython/issues/103551, and [others](https://github.com/python/cpython/issues?q=%22returned+a+result+with+an+exception+set%22), **it looks to me like it was a bug in Python 3.12 alpha 7 itself**, which was since fixed, rather than in GitPython. If that is the case, then this could be closed.

I think it may be worthwhile to use `onexc` conditionally when running on Python 3.12 and later. (The old `onerror` way has to be kept for 3.11 and lower, but it seems to me that using `onexc` where available is still worth doing, primarily because it will automatically work on a future version of Python that removes `onerror`, and secondarily to get clean builds/checks when tools are used that detect deprecated usage.) However, although that appeared related to this issue, I actually think it is independent.
