### ISSUE TITLE
Fix warning in Pyright ("Repo" not exported from module "git")

### ISSUE THREAD

**Issue by DeflateAwning** [gitpython-developers/GitPython#1656]
In Pyright, the following line of code causes the following error:
```python
import git
gitRepo = git.Repo(__file__)
```

Error:
![image](https://github.com/gitpython-developers/GitPython/assets/11021263/a5dc9f1f-000b-454b-8df4-6454099ed4ea)

**Comment by EliahKagan** [comment]
I think this happens because `git.__all__` is built dynamically:

https://github.com/gitpython-developers/GitPython/blob/c8e303ffd3204195fc7f768f7b17dc5bde3dd53f/git/__init__.py#L64

Although `"Repo"` is in it, it's not given literally, and with `pyright` being a static analyzer, it cannot figure that out.

There are some other places where `*` imports are used that I expect might produce a similar effect, albeit for attributes that might be absent rather than attributes that might be considered private.

**Comment by Byron** [comment]
Thanks for posting, and thanks for the analysis @EliahKagan!

Spelling out `__all__` should be easy enough and since GitPython is very stable, I don't think maintaining it would be a problem anymore. Since GitPython started to support type annotation, I think it's worth it to try make it even more useful, to get more mileage out of it.

**Comment by DeflateAwning** [comment]
This issue is resolved with #1659
