### ISSUE TITLE
README rsa key example is flagged by security scanners

### ISSUE THREAD

**Issue by marcm-ml** [gitpython-developers/GitPython#1820]
Hey,

this line is flagged by security scanners (trivy for example). Its a false positive, but maybe you can replace it by some placeholder.

https://github.com/gitpython-developers/GitPython/blob/7ba3fd2a4bd7a384d105ab0a1e4909940a92cda2/README.md?plain=1#L248

https://aquasecurity.github.io/trivy/v0.27.1/docs/secret/scanning/

**Comment by Byron** [comment]
Thanks for bringing this up!

Definitely, let's replace it, and a PR is definitely welcome.

**Comment by EliahKagan** [comment]
Should the [How to verify a release (DEPRECATED)](https://github.com/gitpython-developers/GitPython?tab=readme-ov-file#how-to-verify-a-release-deprecated) section of the README, of which that RSA key is a part, be kept any longer?

It's been marked as deprecated for a while. Are the instructions in it possible to use? If its inclusion is only historical, then it could probably be replaced with a brief note at the end of the preceding section linking somewhere like #77, which is where the deprecation notice links. However, I notice #77 is still open, and from https://github.com/gitpython-developers/gitdb/issues/77#issuecomment-1046418425 I am not sure what, if anything, makes sense to do with it now.

**Comment by Byron** [comment]
It's true - for some reason I was thinking the offending text must be in a source file, but instead it's in a README that tries to explain how to validate a signature.

The public key is also stored in `release-verification-key.asc`, and it seem to not be the same key anymore as in the line 248, but I am unsure about all of it since I don't think it's in use anymore.

Probably it's fine to remove the section entirely even as a quick fix if its applicability can indeed be doubted, which is faster than fixing it for dubious value.

**Comment by marcm-ml** [comment]
Would you want me to make a PR removing the problematic/deprecated section?

**Comment by Byron** [comment]
Yes, that seems like the right thing todo. Thank you.

**Comment by marcm-ml** [comment]
Just out of curiosity, when would you plan the next release which contains the updated README?

**Comment by EliahKagan** [comment]
Should #77 also be considered resolved by #1823? Also, should the existing [`release-verification-key.asc`](https://github.com/gitpython-developers/GitPython/blob/main/release-verification-key.asc), mentioned in https://github.com/gitpython-developers/GitPython/issues/1820#issuecomment-1942375024, be removed too?

**Comment by Byron** [comment]
> Just out of curiosity, when would you plan the next release which contains the updated README?

I will try to create a new release tonight - a lot has changed since the last release so it seems worth it.


> Should the existing [`release-verification-key.asc`](https://github.com/gitpython-developers/GitPython/blob/main/release-verification-key.asc), mentioned in [#1820 (comment)](https://github.com/gitpython-developers/GitPython/issues/1820#issuecomment-1942375024), be removed too?

I would keep it as it probably still can used to verify older release for those who are into it. Those who are interested in verifying signatures will probably know how to use it as well.

With that said, I am sure it will be removed eventually, and I wouldn't even object to a PR that removes it right away either.

> Also, should [gitpython-developers/gitdb#77](https://github.com/gitpython-developers/gitdb/issues/77) in gitdb be considered resolved by the combination of the verification instructions having been deprecated and their removal in #1823? I ask because [gitpython-developers/gitdb#77](https://github.com/gitpython-developers/gitdb/issues/77) had been the readme-linked issue documenting the deprecation, and it doesn't look like there's any recent publicly expressed interest in trying to bring back that kind of verification procedure.

That's a good point! I will close it with reference to this conversation.

**Comment by EliahKagan** [comment]
> I will try to create a new release tonight

In case it comes up and people find this by searching, note that the [CI check failure](https://github.com/gitpython-developers/GitPython/actions/runs/7921741725/job/21627726143) on the release commit 1f37b48 is not related to this or any other changes that went into [3.1.42](https://github.com/gitpython-developers/GitPython/releases/tag/3.1.42), it is just an intermittent failure due to #1676 and it does not reflect a problem in the GitPython library.

> I would keep it *[...]* With that said, I am sure it will be removed eventually *[...]*

This can probably be done at the same time as #1708 -- see https://github.com/gitpython-developers/GitPython/discussions/1708#discussioncomment-7474149 and https://github.com/gitpython-developers/GitPython/issues/1716#issuecomment-1773728098 -- if it doesn't end up being removed before then. That should bring attention back to it even if it has been forgotten.

> That's a good point! I will close it with reference to this conversation.

That issue, https://github.com/gitpython-developers/gitdb/issues/77, is still open, which seems like it may be unintentional.
