### ISSUE TITLE
tests fail if reflog is empty

### ISSUE THREAD

**Issue by moben** [gitpython-developers/GitPython#286]
When the reflog for the current branch has only 1 entry (I don't think "empty" is technically possible), tests fail with

    ======================================================================
    ERROR: test_rev_parse (git.test.test_repo.TestRepo)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/root/GitPython/git/test/test_repo.py", line 654, in test_rev_parse
        assert rev_parse('@{1}') != head.commit
      File "/root/GitPython/git/repo/fun.py", line 233, in rev_parse
        raise IndexError("Invalid revlog index: %i" % revlog_index)
    IndexError: Invalid revlog index: -2
    -------------------- >> begin captured stdout << ---------------------
    failed on 0.1
    failed on 0.2
    
    --------------------- >> end captured stdout << ----------------------

If I for example create an empty commit with

    git commit --allow-empty --message test

they pass.

You can reproduce this easily by cloning the GitPython repo to a new directory.

**Comment by Byron** [comment]
This is a known issue, and is currently overcome by preparing the repository after checkout, on [travis at least](https://github.com/gitpython-developers/GitPython/blob/master/.travis.yml#L18).

Feel free to suggest a solution, however, to me it seems the main culprit is that GitPython uses its own repository in read-only mode at all. This is bad and shouldn't be done, but also speeds up tests considerably.

One could consider rewriting tests to setup their own sandboxes from scratch, but so far I didn't get around that.

Thus, to me this issue is "won't fix", but I am open to suggestions if they don't involve a massive amount of work coming my way :).

**Comment by moben** [comment]
Sorry for forgetting about this.

I don't really have an idea of how to fix this, so we just use something similar to what travis does in our package for now.

**Comment by Byron** [comment]
No need to apologize, I am happy you got it to work on your end.
