### ISSUE TITLE
Cannot make releases on PyPi

### ISSUE THREAD

**Issue by Byron** [gitpython-developers/GitPython#298]
My previous PyPi account was based on OpenID, which is not supported anymore by google. Apparently PyPi didn't care which causes OpenID users to be unable to login to their accounts. 

This renders me unable to make any updates on PyPi, neither to any of my other packages, nor to GitPython.

@empty If you happen to still have access to your account, could you please add `ByronBates` as maintainer to GitPython to fix this issue ?

Thank you.

**Comment by domibarton** [comment]
Hi there! 

Can you make a new PyPi release or is your account still linked to your OpenID?

I'm using GitPython for a script here and need to set an alternative SSH key, which is a bit of a hack in the current PyPi version, because you can't pass an environment dict to the [Repo::clone_from() method](git/repo/base.py#L872). I've to use the "private" `_clone` method to achieve the same result :/

Let me know if I can help you with the PyPi release.

Cheers
Domi

**Comment by Byron** [comment]
The issue described here is still present, unfortunately, and personally I don't believe it will be fixed.

For now I can only recommend to use pip for installation, and provide a git branch/git repository URL instead of a pypi version, to get the latest one that way.

**Comment by empty** [comment]
@Byron I will add you as maintainer.

**Comment by empty** [comment]
@Byron You're now an owner of the GitPython package on PyPi. Let me know if you need anything else. If you need me best to message me @mtrier on twitter. I get way too many emails from GitHub.

**Comment by Byron** [comment]
Thank you ! At last, I was able to create a new version.
This will make people's lives so much easier.

**Comment by empty** [comment]
@Byron I'm really sorry about that. I totally missed this item. I'm glad we got it resolved.
