### ISSUE TITLE
Document string types used by GitPython

### ISSUE THREAD

**Issue by rholy** [gitpython-developers/GitPython#312]
I noticed that starting with GitPython 0.3.4 hexadecimal SHAs are no longer `str`s but `unicode`s. Since the expected type is not documented anywhere (assuming that changelog is not a documentation), users have to guess. A wrong guess may lead to errors in programs. E.g. GitPython 0.3.4 + Python 2.7:

``` python
>>> commit.hexsha + '\xc5\x99'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
```

...this used to work before GitPython 0.3.4. This change also complicated writing programs that needs to be compatible with both GitPython < 0.3.4 and GitPython >= 0.3.4.

**Comment by Byron** [comment]
With the introduction of Python3 support, I believe all strings which are text became `unicode` in python 2, and `str` in python 3.  Everything else is `str` in python 2 and `bytes` in python 3.
With the answer provided in #311 it should be possible to adjust code to deal with both versions of GitPython.

Documenting the types might help those who read documentation, all others will most certainly make things work by trial and error. As python is dynamically typed and string/text handling is inherently difficult in this ecosystem, I feel like I am fighting windmills at best.

Considering the issue was first discovered by you, I'd be glad if you could add the documentation that would help people in a similar situation, and would be glad to merge any PR that make improvements in that matter.

**Comment by rholy** [comment]
Well, if you guarantee that even undocumented features won't change until GitPython 2.0 then there is really no reason to document it. Otherwise, the documentation provides users the definition of the features that are guaranteed to be compatible until next major release of GitPython.
I have no problem with writing a patch once I will have some free time.

**Comment by Byron** [comment]
Great to hear. From my point of view, I don't think there will ever be a version 2.0 of GitPython, and as Pypi locked me out by simply not maintaining the oauth-based authentication mode, I don't think there will be an additional patch release either.

Thus it's very safe to assume that v1.0.1 on Pypi is the definitive and last release, whereas the master branch on GitHub may contain some fixes that interested parties can install using `pip` for example.

**Comment by rholy** [comment]
:-( Are you saying that GitPython is dead? :-( I find it much better than pygit2!

**Comment by Byron** [comment]
I will keep it maintained, but there will be no new features unless these are provided by interested parties via PRs.
It's now as stable as it gets and works everywhere, which can be an advantage.

**Comment by Byron** [comment]
A new release was just made to pypi 😁 (*see #298*) !

**Comment by stsewd** [comment]
Probably It's time to drop python 2 support? I think there are some places that aren't compatible with python 2 right now anyway (test didn't catch them).

If python 2 support is dropped, then this issue can be closed or it still needs documentation? (Or maybe type annotations?)

**Comment by Byron** [comment]
Python 2 support was just dropped, which hopefully facilitates maintenance and additional bugfixes.

<img width="1419" alt="Screenshot 2019-07-20 at 17 34 49" src="https://user-images.githubusercontent.com/63622/61577060-b243e380-ab14-11e9-9bb5-906e2d6fd119.png">
