### ISSUE TITLE
Documentation errors in base.py and test_docs.py

### ISSUE THREAD

**Issue by marianwieczorek** [gitpython-developers/GitPython#314]
revA..revB &rarr; revA...revB (three instead of two dots) [base.py, line 467](https://github.com/gitpython-developers/GitPython/blob/master/git/repo/base.py#L467)

rorepo is a ~~a~~ Repo instance [test_docs.py, line 21](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_docs.py#L21)

**Comment by Byron** [comment]
Hi,

Thanks for letting me know ! In this case I'd like to encourage you to submit a PullRequest, as it is actually easier to just fix it yourself instead of preparing an issue.

The steps to follow would be along these lines:
* fork the GitPython repository
* Add your remote to your local checkout: `git remote add mine https://github.com/marianwieczorek/GitPython`
* make the required changes and commit them
* Push the changes into your fork: `git push mine master`
* Click the green `PR` button in the github interface and follow along to make a PR
* in the PR's description, you could add `closes #314` to close this issue automatically once the PR is merged.

When looking at the bullet points above, it doesn't actually seem easier ... but trust me, it is :).
What do you think ?

Cheers,

**Comment by marianwieczorek** [comment]
I will do it over the weekend. Thanks for responding so quickly. Great work!

**Comment by marianwieczorek** [comment]
... or immediately :-) Sorry for the confusion. I reopen the ticket in order to close it with your PR merge.
