### ISSUE TITLE
Assertion fails when fetching with prune=True

### ISSUE THREAD

**Issue by eswierk** [gitpython-developers/GitPython#32]
I'm occasionally hitting an assertion failure when calling remote.fetch(prune=True). It appears to fail only when some remote-tracking branch is actually pruned. For example:

  File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.2.RC1-py2.7.egg/git/remote.py", line 593, in fetch
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.2.RC1-py2.7.egg/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len("fcf7e70bc1df0fad8b08d088df46c6d778b4579f\tnot-for-merge\tbranch 'master' of github.com:foo/bar\n"]) != len(['   4a2be28..fcf7e70  master     -> foo/master', ' x [deleted]         (none)     -> foo/release'])

Apparently when the remote-tracking branch release was pruned, it was removed from .git/FETCH_HEAD but was still mentioned in the fetch info lines. Maybe lines starting with ' x [deleted]' should simply be removed from the fetch info lines?

**Comment by Byron** [comment]
I was unable to reproduce the issue in the latest version. This makes sense as the [assertion in question](https://github.com/gitpython-developers/GitPython/blob/master/git/remote.py#L538) was changed to be less picky. Also the way the matching of FETCH_HEAD information with progress information works was improved ever so slightly.
In effect, the issue seems resolved.
