### ISSUE TITLE
RootModule.update(force_reset=True) not works as expected

### ISSUE THREAD

**Issue by Un1oR** [gitpython-developers/GitPython#337]
cd /tmp
    mkdir repo submodule

    pushd submodule
    git init
    touch README.md
    git add -A .
    git commit -m 'Initial commit'
    popd

    pushd repo
    git init
    git submodule add --force /tmp/submodule/
    git commit -m 'Initial commit'

    echo FOO > submodule/README.md
    git status
--> modified:   submodule (modified content)

    python
    >>> import git
    >>> repo = git.Repo()
    >>> repo.submodule_update(force_reset=True)

    git status
--> modified:   submodule (modified content)

    git submodule foreach git reset --hard
    git status
--> nothing to commit, working directory clean

**Comment by Byron** [comment]
I think this might be a misunderstanding as `git reset --hard` is not the intended functionality of the `force_reset=True` keyword parameter of `RootModule.update()`. The update functionality aims to dealing with tracking branches of remote repositories in submodules in order to keep the local copy uptodate to changes in the remote, recursively. This is useful if you have a checkout of submodules who are supposed to track their remotes, instead of statically pointing to a single commit.

If this answer is not clear the issue, please feel free to state your concerns and I will reopen it.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/QpZ5pD6QRcs).

*`GitPython #22 [issue 337 - clarify the force_reset flag in Submodule.update]`*

[\![thumb](https://i.ytimg.com/vi/QpZ5pD6QRcs/mqdefault.jpg)](https://youtu.be/QpZ5pD6QRcs)
