### ISSUE TITLE
Cannot get GitPython to connect using SSH executable

### ISSUE THREAD

**Issue by PeteAUK** [gitpython-developers/GitPython#346]
Currently using GitPython 1.0.1 with Git 2.1 and cannot get GitPython to connect using an SSH executable.

My ssh_executable.sh code is as follows:
```
#!/bin/sh
ID_RSA=/home/ec2-user/.ssh/git_rsa
exec /usr/bin/ssh -v -o StrictHostKeyChecking=no -i $ID_RSA "$@"
```

I have proved this works by running this manually: `sudo bash ssh_executable.sh git@github.com`

My python code is:

```
repo = git.Repo(rw_dir)

ssh_executable = '/location/ssh_executable.sh'

with repo.git.custom_environment(GIT_SSH=ssh_executable):
        repo.remotes.origin.fetch()
```

When I execute the fetch it prompts for username and password, changing the ssh_executable doesn't do anything (even pointing it to a non-existent file).  I have tried GIT_SSH_COMMAND and passing `ssh -i "/home/ec2-user/.ssh/git_rsa"'` to both and it still prompts for a username and password.

Any suggestions apart from update Git to 2.3?

**Comment by Byron** [comment]
Thanks for posting, even though I don't think this problem is related to GitPython

When looking at the manual invocation, it strikes me that maybe it doesn't actually work if for you either if you would try it like this: ` ssh_executable.sh git@github.com`.
If that's the case, you should make sure that `ssh_executable.sh` is actually executable, by running a `chmod +x ssh_executable.sh` for instance.

Considering git itself seems to ignore the file entirely, it might just have figured out that the file is not officially executable.

Hope that helps !

**Comment by PeteAUK** [comment]
Thanks for the reply.  `ssh_executable.sh` has been flagged with +x already.

Trying `./ssh_executable.sh git@github.com` does connect through OK - GitHub successfully informs me "Hi!, You've successfully authenticated, but GitHub does not provide shell access."  However when I run the python script it just prompts me for my username & password

**Comment by Byron** [comment]
Thanks for letting me know.

The next thing you could try is how git responds if you call it directly:

```bash
GIT_SSH=/location/ssh_executable.sh git fetch origin
```

This is exactly what GitPython should do under the hood. If it doesn't work on the command-line either, there might some problem unrelated to GitPython.

If it works on the command-line, you might try the latest GitPython version from github, just to be sure this is not due to some issue that was already fixed in the meanwhile.

Thanks for your feedback.

**Comment by PeteAUK** [comment]
Apologies on the delay.  Running the above still prompts for a username and password in the same way as if I'd not specified an SSH executable.

**Comment by Byron** [comment]
I am sorry to hear that.
As there are unit-tests which confirm that git will execute such a file through GitPython, I have reason to believe the issue at hand is not related to GitPython.

It should work with the example given above - if you can make this work on the command-line, it will work in GitPython as well.

Good Luck !

**Comment by PeteAUK** [comment]
Finally made that "break through".  You're completely right in that it's relating to Git rather than GitPython.  If you use https to connect to a git repository, it will completely ignore any SSH settings configured.

**Comment by Byron** [comment]
Thanks for posting your resolution here ! It will be very helpful next time someone has a similar problem !
