### ISSUE TITLE
commit all untracked changes, including deleted files

### ISSUE THREAD

**Issue by nschloe** [gitpython-developers/GitPython#351]
For committing all untracked changes (`git commit -a`) in GitPython, you have to add all dirty files to an index
```
index.add([diff.a_blob.path for diff in index.diff(None)])
```
and commit that (according to [this answer on the mailing list](https://groups.google.com/forum/#!topic/git-python/oUwoWC8lt8o) from 2011).

Unfortunately, this doesn't work if there are deleted files. In this case, one gets
```
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/deleted/file.txt'
```
Any way for dealing with this?

**Comment by Byron** [comment]
`IndexFile.add(...)` is not suited for possibly non-existing resources due to the behaviour you experienced already.
In your case, I believe it would be best to just call git directly like this: `repo.git.add(update=True)`. `repo` is assumed to be the `Repo` instance from which you previously obtained the `index` as well.

Next time you have a question, you might want to consider using stackoverflow with the `GitPython` tag as this will drastically reduce the time it takes to receive a suitable answer.

If this works for you, please feel free to close this issue.

**Comment by nschloe** [comment]
Is there a corresponding piece of documentation that you could point me to?

**Comment by Byron** [comment]
There is a part of the tutorial dedicated to using `git` directly: http://gitpython.readthedocs.org/en/stable/tutorial.html#using-git-directly.

Using the git command's porcelain is the recommended way of doing high-level tasks in GitPython.
