### ISSUE TITLE
GitPython is unable to locate repository top-level directory

### ISSUE THREAD

**Issue by larsks** [gitpython-developers/GitPython#386]
Given:

    >>> import os
    >>> import git
    >>> os.listdir('.')
    ['.git', 'file1', 'dir1']

This works just fine:

    >>> r = git.Repo('.')

But I was surprised that this didn't work:

    >>> os.chdir('dir1')
    >>> r = git.Repo('.')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 167, in __init__
        raise InvalidGitRepositoryError(epath)
    git.exc.InvalidGitRepositoryError: /home/lars/tmp/repo/dir1

I was hoping that GitPython would implement the same search path that
the `git` command lines tools do for locating the top-level repository
directory.  I realize I can implement this myself in my own code, but it seems as if
pretty much *everybody* is going to have to do this, so having this
capability in the module would be tremendously useful.

**Comment by Byron** [comment]
Are you sure this occurs with the latest version as well ? I do vaguely remember a regression like this from the past, and believe it has been fixed for a long time now.

Otherwise, you might want to try turning on the feature by setting [the respective kwarg](https://github.com/gitpython-developers/GitPython/blob/121f6af3a75e4f48acf31b1af2386cdd5bf91e00/git/repo/base.py#L122).

**Comment by Byron** [comment]
Closed due to inactivity. Please comment to get the issue reopened.
