### ISSUE TITLE
remote.pull prints Already up-to-date.

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#437]
The command print "Already up-to-date" to the console.

It seems that problem is the use of with_stdout=False that then does not both to do anything to stdout.

[git-python-with-stdout.txt](https://github.com/gitpython-developers/GitPython/files/275304/git-python-with-stdout.txt)

The attached patch seems to fix the problem by setting stdout to DEVNULL. Tested on python 3.4.

**Comment by Byron** [comment]
I believe it's the default and expected behaviour to use the parent-process file handles in subprocesses. Thus stdin and stdout will be cloned from the terminal in some cases.

However, the way the parameter is documented indicates the intention was different: `If True, default True, we open stdout on the created process`, and I guess otherwise you don't show anything.

Unfortunately `DEVNULL` is only available in python >=3.3, and the alternative, `popen(stdout=open(os.devnull, 'wb'), ...)` leaves me puzzled about who is going to close the opened file-handle.

Do you have any information on this ? Opening a stderr permanently and reusing the file-handle would be easy enough, but at least I'd like to know what this means for resource handling.

In the meanwhile, I will test it a little more.

**Comment by Byron** [comment]
Great, it looks like Popen takes care of the details automatically for you, and closes the freshly opened file-handle (or transfers it to the subprocess, who knows).
