### ISSUE TITLE
Travis CI does not process for Python 2.6

### ISSUE THREAD

**Issue by andy-maier** [gitpython-developers/GitPython#458]
The `.travis.yml` file specifies `"2.6"` but all Travis runs I checked did not actually run it.

**Comment by andy-maier** [comment]
I don't really have an explanation why it would not run 2.6.

Travis CI generally supports Python 2.6. In the pywbem/pywbem project on GitHub, we specify 2.6 and it also runs.

Comparing the two `.travis.yml` files, I see two differences:

- sudo required (runs in virtual system) in pywbem file vs. not required (runs in container) in gitpython file.
- matrix entry in gitpython file specifying allow_failures for python 2.6.

**Comment by Byron** [comment]
I cannot see the issue - here is a [link to travis](https://travis-ci.org/gitpython-developers/GitPython/jobs/134373179) showing the issue python 2.6 currently has. From my point of view, it is working as expected.

Please feel free to leave a comment in case reopening this issue is required.
Thank you

**Comment by andy-maier** [comment]
I agree that it works as intended.
I simply missed the python 2.6 run shown further down on the travis page. Sorry for my confusion.
