### ISSUE TITLE
Deleted file showing as new file

### ISSUE THREAD

**Issue by craigcabrey** [gitpython-developers/GitPython#466]
I'm running into a problem where a deleted file is showing as new. I reproduced the issue to the best of my ability below.

Repository: https://github.com/apache/httpclient.git
Commit: [`b29c819645a404a064f022d5a75d8597985f6fac`](https://github.com/apache/httpclient/commit/b29c819645a404a064f022d5a75d8597985f6fac)

Using Python 3.5.1, GitPython 2.0.5, and git 2.8.3.

```python
import git

repo = git.Repo('.')
commit = repo.commit('b29c819645a404a064f022d5a75d8597985f6fac')
diffs = [diff for diff in c.diff(c.parents[0]) if 'AbstractVerifier.java' in diff.a_path]

print(diffs) # [<git.diff.Diff object at 0x7f6786634748>]
print(diffs[0].deleted_file) # False
print(diffs[0].new_file) # True
```

**Comment by nvie** [comment]
You're running the diff the wrong way around. GitPython follows the order of arguments to that command line git diff would also require: old -> new. So you should use `c.parents[0].diff(c)` rather than `c.diff(c.parents[0])`. That's why you get the inverse. It's definitely not super intuitive, but that's how it works.

**Comment by craigcabrey** [comment]
Thanks for the tip, appreciate it.
