### ISSUE TITLE
`is_dirty` for directory

### ISSUE THREAD

**Issue by haizaar** [gitpython-developers/GitPython#482]
I have a feature request: it will be useful to have something similar to `git status <path>` that returns which files are modified, untracked, etc. - in the give directory only.

Similar to `repo.is_dirty()`, but something that accepts path as well.

The usecase: we use git commitish to generate docker tags, and need to know whether a particular module directory is dirty.

**Comment by Byron** [comment]
As GitPython in currently in maintenance mode, new features are only added via PR. One way to go about this issue is to flesh out how you want to use it, with enough examples to indicate how it should work, and then hope somebody comes along and implements it. Alternatively, you can implement it yourself. If you see neither of this happening, I believe it would be best to close this issue instead of leaving it open for eternity. What do you think about this ? Or are there other options ?

**Comment by haizaar** [comment]
Hi Byron,

I think this is something I'll implement myself in the next couple of weeks.

P.S. Do you know any other git-python project that is active?

**Comment by Byron** [comment]
Even though `dulwich` comes to my mind, I didn't really work with any of these (including GitPython) for years now. I will leave the issue open then, and mark it accordingly.

**Comment by haizaar** [comment]
Hi Byron,

I created a [PR](https://github.com/gitpython-developers/GitPython/pull/496) (including unittests). Please review.
