### ISSUE TITLE
NameError: name 'Repo' is not defined

### ISSUE THREAD

**Issue by DhananiK** [gitpython-developers/GitPython#486]
I have already installed the package and when I try to run:

```
from git import *

repo = Repo("/Users/USERNAME/desktop/test")

```

I receive this error:

```NameError: name 'Repo' is not defined```

**Comment by Byron** [comment]
What happens when you execute `print(git)` after importing it with `import git` ? Doing so should show that the `git` module you see is not GitPython.
It would be interesting to know which package is in the way, maybe there is some sort of package-nameclash that we should all be aware about.
Maybe overly confident, but I believe closing the issue pre-emptively is fine - otherwise please feel free to comment to get it re-opened.
