### ISSUE TITLE
Parse tag fail for some tag info.

### ISSUE THREAD

**Issue by hwchiu** [gitpython-developers/GitPython#503]
Environment
--------------
- Git: 2.9.1
- GitPython: master branch (2016-08-26)
- Target project:
    - [openvpn](https://github.com/OpenVPN)

Status
-------
- Use the GitPython to parse the tag info of openvpn.
- The tag v2.2-beta1 will cause the wrong data structure
    - The repo.tags[xx] should return the TagReference object.
    - The repo.tags[xx].commit should return the Commit object.
    - when the tag v2.2-beta1 be loaded
        - The repo.tags[xx].commit still be the TagObject object rather than Commit object.
- Result of the 'git show v2.2-beta1'
    - [gist](https://gist.github.com/hwchiu/b63e7588ff331a6d6c5ef38487718930)
- Reason
   - Maybe there are two "tag v2.2-beta1" in the show info will cause the parse error ?

My Code
----------

``` python
import git

repo = git.Repo.clone_from('....' , '...')
test = sorted(repo.tags, key=lambda t: t.commit.committed_date)


Error:
  File "/usr/local/lib/python2.7/dist-packages/gitdb/util.py", line 239, in __getattr__
    return object.__getattribute__(self, attr)
AttributeError: 'TagObject' object has no attribute 'committed_date'
```

Is it a bug ?  or Do you have any suggestion I can do in my application to get all tag by date?

Thanks.

**Comment by Byron** [comment]
@hwchiu Thanks for this great example of an issue - I could easily reproduce it. Digging into the code I found [this line](https://github.com/gitpython-developers/GitPython/blob/df65f51de6ba67138a48185ff2e63077f7fe7ce6/git/refs/tag.py#L30), which states:
```python
        elif obj.type == "tag":
            # it is a tag object which carries the commit as an object - we can point to anything
            return obj.object
```
However, in any case, the API is not delivering on its promise of only returning `commit` objects, which should be fixed in some way.
We could throw an exception, similar to what already happens in the `tree` or `blob` case.
Thus it seems it is up to the caller to determine what kind of object that `commit` actually is, and the example code would then probably look more like this:
```python
sorted(repo.tags, key=lambda t: safe_commtted_date_of(t.object))
```

**Comment by Byron** [comment]
Alternatively, it could recursively resolve the commit, assuming that eventually it will find one. This is certainly the better fix, which I am going for.
