### ISSUE TITLE
Can not run fetch with ssh key with passphrase

### ISSUE THREAD

**Issue by sashadereh** [gitpython-developers/GitPython#559]
Hello, I can not run fetch using ssh key with passphrase. I have a script like this:

```python
_REPO_PATH = "C:\my_git_repo"
_SSH_EXECUTABLE = "ssh_executable.py"
_SSH_EXECUTABLE_PATH = os.path.join(os.path.expanduser("~"), ".ssh", _SSH_EXECUTABLE)
repo = git.Repo(repo_path)
repo.git.update_environment(GIT_SSH=_SSH_EXECUTABLE_PATH)
fetch_results = repo.remote('origin').fetch()
```

Output of this script is

```
git pull remote origin failed (Cmd('git') failed due to: exit code(128)
cmdline: git fetch -v origin
stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.')
````

Contents of `ssh_executable.py`
```
#!/usr/bin/python

import os
import sys
import subprocess
import traceback

with open(os.path.join(os.path.expanduser("~"), ".ssh", "test_file"), 'w') as outfile:
	outfile.write("Run script\n")
	try:
		outfile.write('Environ = %s\n' % os.environ)
		ssh_options = ['-i', os.environ['GIT_SSH_KEY']]
		outfile.write("Args: \n%s\n%s" % (str(ssh_options), str(sys.argv[1:])))
		outfile.write('\n')
		subprocess.call(['ssh'] + ssh_options + sys.argv[1:], shell=True)
	except Exception as e:
		outfile.write("Exception: %s" % e)
		outfile.write("Traceback:\n%s" % traceback.format_exc())
```
File `test_file` is created, when I run the script, so it is executed.

If I run 
```
cd /c/my_git_repo
GIT_SSH=~/.ssh/ssh_executable.py git fetch -v origin
```
via git MINGW console I will be asked for a password and then everything will be Ok. So, I expect, that when I run my script it will ask passphrase of my key also, but it just fails.
I rechecked, that my GIT_SSH_KEY environment variable contains right path to my key. Also, it has the name `my_key`, not `id_rsa`.
I'm running Windows 10.

Thanks.

**Comment by Byron** [comment]
Thanks for the detailed description of the problem.

As far as I know, it is not possible to use keys with passphrases with GitPython due to the way git is invoked by it. It simply does not connect standard input, which usually would be required to read the passphrase. The preferred way to do it would be to use a specific key without passphrase.

If that is not an option, git will also invoke the program pointed to by `GIT_ASKPASS` to read a password for use with the ssh key.

Maybe the hints above can help you fix the problem.
For now I am closing the issue as I don't think GitPython can reasonably provide a fix. However, please feel free to comment with additional questions or just to get it re-opened if you think differently about it.
