### ISSUE TITLE
Update function of RemoteProgress lags for gitlab case.

### ISSUE THREAD

**Issue by chrispe92** [gitpython-developers/GitPython#583]
Hello all,

I have been recently been trying to use the RemoteProgress class (Python 3.4) to update the current progress of a git clone. I have noticed that the messages are updated only once the status of a stage has reached 100%. I did have the same issue without the use of a lock, so I suppose it's not a thread-safe issue.

The issue seems pretty similar to this: https://github.com/gitpython-developers/GitPython/issues/145

You can see my use case here:
````
class Progress(RemoteProgress):
    def __init__(self, username, project_name):
        RemoteProgress.__init__(self)
        self.username = username
        self.project_name = project_name

    def update(self, op_code, cur_count, max_count=None, message=''):
        global import_sessions
        lock.acquire()
        try:
            if self.username in import_sessions:
                if self.project_name in import_sessions[self.username]:
                    import_sessions[self.username][self.project_name]['message'] = self._cur_line.splitlines()[-1]
                    import_sessions[self.username][self.project_name]['progress'] = int(100.0 * cur_count/(max_count or 100.0))
        finally:
            lock.release()`

**Comment by Byron** [comment]
I am not quite sure that #145 relates to this issue, as it was talking about the git process hanging entirely due to unconsumed content of pipes. The problem stated here is that all progress happens to come in at the very end of the git-progress, which defeats the purpose.

The way I see it, asynchronous handling of progress [should work](https://github.com/gitpython-developers/GitPython/blob/88732b694068704cb151e0c4256a8e8d1adaff38/git/cmd.py#L110), provided you are using the latest version of GitPython.

Is this the case?

**Comment by Byron** [comment]
Closed due to inactivity - please feel free to comment or reopen if the interest is rekindled.
