### ISSUE TITLE
Is git.Repo.iter_commits() threadsafe?

### ISSUE THREAD

**Issue by regisz** [gitpython-developers/GitPython#584]
I would like to use multiprocessing.pool.ThreadPool to get more commits parallel (`ThreadPool.map` function). If I allow more than 1 threads then I get the next exception:
`ValueError: SHA tree could not be resolved, git returned: 'tree 2d094d5f2032448e3c0fd06ae297ffdebd0ddfb4'`

What is the problem? Is it not threadsafe?
Thx!

**Comment by Byron** [comment]
By default, you must assume nothing in this library (or any other one, for that matter), to be thread-safe.
If done anyway, each thread should at least have its own repository instance. Then the contention will be moved to the file-system, which at least _should_ be OK due to the usage of lock-files.
However, I do advice against trying to write and read at the same time from multiple threads, as it is asking for trouble.
Even though I am closing this issue, please feel free to keep commenting.

**Comment by regisz** [comment]
I tried to read only, but it caused problems, unfortunately. I will try to use own repository instance for all threads, but it not unequivocal because I would like to iterate over a range used Repo.iter_commits(). Thx your answer!

**Comment by fabiosangregorio** [comment]
I spent the last two days trying to understand what concurrency problems I was having in my code when doing exactly this. Turns out the `diff` method is not thread-safe either.
