### ISSUE TITLE
When fetching, can't include commit SHA as source in refspec

### ISSUE THREAD

**Issue by cool-RR** [gitpython-developers/GitPython#592]
I'm moving all of my Git code from launching Git with subprocess to using GitPython. Most of the transition  was easy, but there are a couple of things I can't figure out how to do, this is one of them.

I have code that launches `f'git fetch my_remote {commit_sha}:{my_branch}'` . This succeeds when done with regular Git, but fails with GitPython: `TypeError: Cannot handle reference type: "'8cf10366155b4cb1ce9f2fbeefa4227872c7bdef'"`

I also tried it on an isolated example outside of my project and on a different computer. It still fails with GitPython but succeeds with command line Git.

**Comment by Byron** [comment]
If you believe this is a bug, you will have to provide a [MCVE](http://stackoverflow.com/help/mcve) in order to reproduce it.
In case you get into issues like this, you should always be able to resort to using git directly via `repo.git.*`.
Due to the high rate of issues created by you, I prefer to close them, but would reopen if the required feedback is provided.
