### ISSUE TITLE
submodule.move not documented and doesn't update all refs

### ISSUE THREAD

**Issue by mikelikespie** [gitpython-developers/GitPython#69]
Hi,

I am trying to make submodule moving easy.

submodule.move seems to get me half the way there, but it misses a couple things.  In new versions of git the .git is just a textfile that references a path in the base directory.  This file isn't updated if you move directory depths because it is relative.

It also doesn't update the submodule name in the .git/config which would be helpful.  I'll probably be writing the code to do this, but documentation on submodule.move would help too.

Thanks,
Mike

**Comment by Byron** [comment]
In the latest revision of master and the upcoming release v0.3.6, this issue will be fixed so that .git files are fully supported. During move, these files will be rewritten with the respective relative path.

The second part of this issue, automatically renaming submodules during move, is something I will implement when doing #238. It will only be automatic if the submodule name equals the previous submodule checkout path.

I will close this issue once the linked issue is closed.

**Comment by Byron** [comment]
You can watch the archived development stream on youtube:

* [part 1](http://youtu.be/Zw300x0t2Ow)
* [part 2](http://youtu.be/mFupbFIf8r0)
