### ISSUE TITLE
New GitPython release to include fixes in #689

### ISSUE THREAD

**Issue by theckman** [gitpython-developers/GitPython#704]
Hi @Byron,

Thank you so much for your hard work on coordinating the efforts of this project. I've run in to the issue fixed by #689, and subsequently noticed comment about getting a new release ready:

* https://github.com/gitpython-developers/GitPython/pull/689#issuecomment-345523032

I definitely don't want to come across as trying to prescribe how to organize your project and releases, and I understand that there are some things to be done for the next release. To make it a little easier for you, I wonder if you'd be willing to release a `v2.1.8` that includes only the changes in #689?

If your preference is to finish the other things first, no sweat and I'm happy to wait for the next release. I only wanted to open an issue so that any of us who are affected can follow, so we can get an email when the next is release pushed out. :)

Thank you again for your time and work on GitPython.

**Comment by alexreg** [comment]
I certainly concur with this. Apologies for hassling you @Byron, but any chance of a new release shortly? :-)

**Comment by ankostis** [comment]
+1 m
No need to hurry an important release, but certain users can't wait for it either.

**Comment by christianromney** [comment]
Is there anything a new contributor might be able to do to make it possible for you to cut a hotfix release? Like everyone else who benefits from your open source contributions, I'm very grateful for your work and the generosity of your time. We all know how difficult it can be to dedicate personal time to open source projects, which is why I am offering assistance in getting a release out if it can be of any help. This package's success means that a lot of widely used software depends on it. Many users' tools are now broken. As one of these users, I would be very grateful for a point release that allowed me to continue to use these tools without having to wait for new feature development or broader maintenance efforts to be completed. Again, I hope I have conveyed a sense of gratitude and not entitlement while also stressing the impact this issue is having on many of the beneficiaries of your work. Thank you.

**Comment by Byron** [comment]
Hi everyone,

sorry for the long time you have to spend waiting between the releases, for which I am still the bottleneck. These days I am quite hesitant to catch up on this project, as I basically lost all connection with it.
However, in future this might get a little better, as @yarikoptic and @ankostis are helping out a lot and single-handedly keep the commits coming. Just today @yarikoptic gained the capability to sign and make releases to pypi himself, and I would happily allow @ankostis to do the same.

That way this project should be better prepared to get releases out at a faster pace.

All the best,
Byron

PS: I leave closing the issue to @theckman once the new releases is actually out.

**Comment by jgavris** [comment]
@theckman We can close this one now? 🎉

**Comment by theckman** [comment]
Yep. This can definitely be closed. Thank you to everyone who helped.
