### ISSUE TITLE
Thank you GitPython devs

### ISSUE THREAD

**Issue by mattmakai** [gitpython-developers/GitPython#709]
Hey folks, thank you for the awesome work you're doing on this library. I've been using GitPython to snag all my commit data out of local repositories to build a Django+Bokeh-based data dashboard application. I have really enjoyed working with your code.

I extracted bits of my application to create a quick [First Steps with GitPython](https://www.fullstackpython.com/blog/first-steps-gitpython.html) blog post for Full Stack Python to help other devs learn about your project.

There's no actual issue here, I just wanted to say thanks. You can close this issue ticket whenever.

**Comment by vfulco** [comment]
+1

**Comment by Byron** [comment]
@mattmakai Thank you very much :)! It's always nice to see your project being used and useful to others, even though at some point it might become a burden.
In order to not let it become a burden to the users, I try to set it up with more maintainers to be able to perform all operations, from merging PRs to cutting a release.
@ankostis and @yarikoptic have helped tremendously with the next release, and I hope they feel addressed by this issue, too :)!

**Comment by stephaniemdavis** [comment]
I'm a late comer on GitPython but wanted to thank its developers AND @mattmakai for bringing it and its capabilities to the attention of the broader Python-development community!
Happy New Year.
