### ISSUE TITLE
Broken link "Edit on GitHub"

### ISSUE THREAD

**Issue by scls19fr** [gitpython-developers/GitPython#754]
Hello,

http://gitpython.readthedocs.io/en/stable/tutorial.html
have a broken link "Edit on GitHub" which link to
https://github.com/gitpython-developers/GitPython/blob/88687342f3bcd261d7e9170b998001fccd563768/doc/source/tutorial.rst

Maybe doc should be updated

Kind regards

**Comment by hsiaoyi0504** [comment]
Just to share some related material here:
- Remove the link
https://github.com/sphinx-doc/sphinx/issues/2386
- Try fix the link
https://gist.github.com/mgedmin/6052926

**Comment by hsiaoyi0504** [comment]
The problem seems to only happen at stable version of doc.

**Comment by Byron** [comment]
Thanks for letting us know!

I tried to reproduce it and noticed that by now, the link described in the issue points to https://github.com/gitpython-developers/GitPython/blob/6c2446f24bc6a91ca907cb51d0b4a690131222d6/doc/source/tutorial.rst , which works as advertised.
Please chime in if there is something else we should look at, or if you think the issue was erroneously closed.
