### ISSUE TITLE
some hooks are tried to be executed even if there is no such a file

### ISSUE THREAD

**Issue by KOLANICH** [gitpython-developers/GitPython#771]
For example https://github.com/gitpython-developers/GitPython/blob/0857d33852b6b2f4d7bc470b4c97502c7f978180/git/index/base.py#L941

May be the cause of 703

**Comment by Byron** [comment]
This is not true - [it checks for accessibility inside that function](https://github.com/gitpython-developers/GitPython/blob/ce5dfe7f95ac35263e41017c8a3c3c40c4333de3/git/index/fun.py#L71-L72).

Even though this ticket is closed, please feel free to state the underlying problem so people can chime in and help.

**Comment by KOLANICH** [comment]
>This is not true - it checks for accessibility inside that function.

That's strange. Windows 7, 32-bit. On popen it fails with a window appearing saing that the hook file is not win32 application. In fact there was no such a file at all in the `hooks` dir.

**Comment by Byron** [comment]
It is strange indeed. If you can provide a simple python script that reproduces the issue, it truly is a bug worth fixing. Might just be very special behaviour on a OS whose tests are known to be broken for GitPython.

**Comment by EricMoorman** [comment]
If anyone is still following this, I had a similar error to this, but with run_commit_hook('post-commit', self) instead of pre-commit.  What I have done to fix the error is to convert the post-commit file in .git folder to a .bat file. The error of the system complaining that the file is not a Win32 application comes from the fact that Windows doesn't like executing files. This resolution seems a little hacky to me, so if anyone has a better solution that would be great.
