### ISSUE TITLE
"Meet the Repo type" example improvement

### ISSUE THREAD

**Issue by solvingj** [gitpython-developers/GitPython#787]
New to this library and just want to ask for feedback before submitting a PR.  

The "Meet the Repo type" example below shows how to create an instance of `Repo`, but it does so by depending on an already created `Repo` instance in some bespoke outer scope.  It then spends 3 lines of comments explaining the what `rorepo` is, and that it's completely unnecessary for the example.  Most importantly, the user cannot simply copy and paste the example and run it locally. 

```
from git import Repo

# rorepo is a Repo instance pointing to the git-python repository.
# For all you know, the first argument to Repo is a path to the repository
# you want to work with
repo = Repo(self.rorepo.working_tree_dir)
assert not repo.bare
```

Is there a reason this example is not something simpler like below?
```
import os
from git import Repo

repo = Repo(os.getcwd())
assert not repo.bare
```

**Comment by Byron** [comment]
Thanks for taking the time to dig into this! I do agree, it can be as simple as that, and when changing it just be sure you are running the tests and verify they still work.
As all examples are tested, there are some limitations on what can be done, but please feel free to experiment.

Please close this issue if the answer is satisfactory, otherwise I will be happy to answer follow-ups.
