### ISSUE TITLE
Inconsistent results from 'git --grep' command 

### ISSUE THREAD

**Issue by anrchen** [gitpython-developers/GitPython#828]
**Description**
I get different results from the following executions, please let me know if I'm missing something:
_GitPython_
```
def get_commit(key, repo):
    repo = git.Repo(repo)
    git_command = ["git", "rev-list", "--all", "--grep="+key]
    result = repo.git.execute(git_command)
    return re.findall('[0-9a-f]{40}', result)
```
_Git_
```git rev-list --all --grep=key```

**Step to reproduce**
- from [zookeeper repository](https://github.com/apache/zookeeper)
- grep for key=ZOOKEEPER-1496 (e.g., `git rev-list --all --grep=ZOOKEEPER-1496`)
- GitPython only returns `d612bb4cca0f916b055ed49bc4845dc71b699740`
- Git command gives
```
d612bb4cca0f916b055ed49bc4845dc71b699740
10705ba6e763eade42e8a2e54acabc181f5b2400
139d1d9c4b78424708b01f239211ed83e9279fc6
```
**Environment**
- GitPython 2.1.11
- Python 2.7.15

**Comment by Byron** [comment]
Thanks, @anrchen , for this example of an issue, and sorry for the late reply!

Here is the output of my interactive session, trying to reproduce the issue:
```python
GitPython git:(master) ✗ python
Python 2.7.16 (default, Mar 11 2019, 10:12:01)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
>>> import re
>>> repo = git.Repo("zookeeper")
>>> repo
<git.Repo "/Users/sthiel/dev/GitPython/zookeeper/.git">
>>> git_command = ["git", "rev-list", "--all", "--grep=ZOOKEEPER-1496"]
>>> result = repo.git.execute(git_command)
>>> re.findall('[0-9a-f]{40}', result)
[u'd612bb4cca0f916b055ed49bc4845dc71b699740', u'10705ba6e763eade42e8a2e54acabc181f5b2400', u'139d1d9c4b78424708b01f239211ed83e9279fc6']
```

By the looks of it, it yields the results you would expect. This makes sense, as `repo.git` really just calls git without any additional logic. However, there may be differences compared to interactive session if the git executable is affected by configuration files or environment variables.

This might give you a hint at what to look into next in order to resolve the problem locally. The documentation [about debugging gitpython](https://gitpython.readthedocs.io/en/stable/tutorial.html#git-command-debugging-and-customization) might be helpful to you.

Please feel free to comment or request to reopen the issue as you see fit.
