### ISSUE TITLE
NameError: name 'self' is not defined in GitPython Tutorial

### ISSUE THREAD

**Issue by aaronlelevier** [gitpython-developers/GitPython#847]
There's an error in https://gitpython.readthedocs.io/en/stable/tutorial.html#tutorial-label

<img width="751" alt="screen shot 2019-02-23 at 12 43 37 pm" src="https://user-images.githubusercontent.com/5514112/53291482-dddebf80-3768-11e9-81f3-cd013c3958ea.png">

**Comment by jeshan** [comment]
Next line in the doc reads:
`In the above example, the directory self.rorepo.working_tree_dir equals /Users/mtrier/Development/git-python `

**Comment by CptMikhailov** [comment]
I vote that we close the issue, seeing this is not an issue. However, I do think that example is awful, and easily has the potential to confuse new users and less-experienced developers. So perhaps a new issue should be opened to discuss revising the tutorial.

**Comment by Byron** [comment]
I agree that this example can confuse new users, and this issue is a proof for that. Currently using `self.rorepo` is a technical requirement, as the documentation is run to assure it functions as advertised.
As @CptMikhailov suggests, an issue to drive revising the tutorial would be the way to go forward. 

The comment by @CptMikhailov is fantastically constructive and drives this conversation forward, and it would be even more effective without the mention of the word `awful`.

**Comment by curiouscod3** [comment]
repo = Repo('.') # for current dir

**Comment by smkplus** [comment]
before using **GitPython** Make Sure you have a repository on path
if you haven't a repository use this command ```git init```
