### ISSUE TITLE
How do you rebase?

### ISSUE THREAD

**Issue by EdwardJB** [gitpython-developers/GitPython#905]
The documentation doesn't mention the term.

**Comment by jeking3** [comment]
Let's assume you have your own fork.  In your fork, you have a branch that is stale with respect to origin/master.

1. get fetch --all
2. git checkout <your branch>
3. git rebase origin/master

What will this do in step 3?

A. Rewind your local branch.
B. Catch your local branch up to origin/master.
C. Re-apply any local commits in the same order, but on the tip.

Once you rebase, your history is different than your fork's history on said branch, so when you push you need to do a push --force in order to overwrite your fork's branch contents.

**Comment by Byron** [comment]
Rebasing is a complex operation provided by the 'porcelain' of git itself. As GitPython is 'plumbing', it doesn't provide the `rebase` operation directly, but the tools to manually implement it.
However, for most cases, it should be enough to run `git` through GitPython, such as in `Repo('/repo').git.rebase()`. For more information, please see the docs about [how to run git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

Even though this issue is closed, please feel free to keep commenting if you need any clarification.
