### ISSUE TITLE
Release notes for 3.0 missing

### ISSUE THREAD

**Issue by jebob** [gitpython-developers/GitPython#921]
I cannot find the release notes for 3.0. https://gitpython.readthedocs.io/en/stable/changes.html only documents 2.x

**Comment by Byron** [comment]
Indeed, the readthedocs page wasn't updated since GitPython 2.1.13 for some reason. The [changes](https://github.com/gitpython-developers/GitPython/blob/master/doc/source/changes.rst#L6) have been updated for each release, and I am not sure what caused readthedocs to stop updating.

I will have a look at the repository configuration, maybe certain hooks stopped working.

**Comment by Byron** [comment]
I think it is fixed now.
Thanks a lot for reporting!
