### ISSUE TITLE
Unable to perform--no--index option  on diff 

### ISSUE THREAD

**Issue by shyamsubbu** [gitpython-developers/GitPython#941]
git --no-pager diff --no-index /path1 /path2 >> gitdiffdata.txt

**Comment by Byron** [comment]
_Maybe this was submitted too early by accident?_

It's unclear to me what this issue is about. And even if it would be clear, the issue is not calling for a change or improvement, it merely makes a statement.

As GitPython maintenance is based solely on volunteers, please consider updating the issue so that a another party can pick it up.
Thank you

**Comment by shyamsubbu** [comment]
when wants to take diff outside git tree . In git command one can give two paths and provide a flag named --no-index
But with gitpython i am unable to excercise the option.

**Comment by Byron** [comment]
Thank you. Can you also provide some code showing how GitPython was used?

**Comment by Byron** [comment]
As part of spring cleaning, I am closing this issue as it was opened more than half a year ago while still asking for feedback.

If this is a mistake or any other action should rather be taken, please let me know in the comments or create a new issue as digest of this one.
Thanks for your understanding and the work that undoubtedly went into this.
